### ISSUE TITLE
An Example of Importing to pure JS file or HTML file

### ISSUE THREAD

**Issue by mimranfaruqi** [stephan-nordnes-eriksen/BOB#1]
Hi, while you have amazed me with great examples and they would be enough for better players. I am, however, trying to utilize this with Microsoft Blazor while using JavaScript files to generate some code from this. To do this, I would need to import this into *.js files and call new BOB()... to generate the stuff and return from the .js function.

Also, if I am embedding this in HTML file, like you gave example for Header tag, can I simply call new BOB() in the script tag within HTML body?

It is not an issue, If you add just an example, I would be honored. :)

Thank you!

**Comment by stephan-nordnes-eriksen** [comment]
Hi @mimranfaruqi! I'm not familar with Microsoft Blazor, but BOB is just pure javascript which returns javascript strings. It is a helper-library to build html strings. In theory you should be able to use it with any system that runs javascript.

If I understand you correctly, and you want to embed this into a HTML, you could for instance set the `innerHTML` of an object.

Eg.:
Somewhere in your HTML
```html
<!-- somewhere in header -->
<script src="path/to/BOB.standalone.min.js"></script>
<!-- somewhere in body -->
<div id="myDiv"></div>
<!-- some place in html -->
<script>
  let data = ["Team member1", "team member2", "team member3"]
  let compiledString = new BOB("ul").do(data).insert("li.team").content(BOB.data).s()
  document.getElementById('myDiv').innerHTML = compiledString
</script>
```

If you use this together with some kind of server-side render, you could do this before, but you would have to run javascript on your server, so Node.js or similar. 

Hope this helps :) 

Also; please forgive the aging state of the repo, as I have not been able to work on this project for some time.

**Comment by mimranfaruqi** [comment]
Thank you 👍 And definitely no worries about aging state, much appreciated the already completed code 💯

**Comment by stephan-nordnes-eriksen** [comment]
Assuming this is resolved, so closing tomorrow unless there is anything else you want to know :)
