### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by mvahowe** [stephan-nordnes-eriksen/BOB#2]
I'm looking for a good way to produce HTML/XML from JS and your module looks like a good fit. I'm going to kick the tyres some more. In the meantime, I have a small PR I could submit which fixes some typos in the (generally excellent) documentation - please see attached.

This module would be much easier to use (and more likely to gain traction) if it were in NPM. Regarding the name, two arcane routes, in the tradition of BASH, would be `robert` and `genuflect`. But `bob-html` would work too.

[README_md.txt](https://github.com/stephan-nordnes-eriksen/BOB/files/5970835/README_md.txt)

**Comment by stephan-nordnes-eriksen** [comment]
I have not seen this issue until today. I'm very sorry. I made this library a long time ago, and have not followed up.

Please feel free to submit a PR directly to the repo so that you can get your deserved internet-cred :)

**Comment by stephan-nordnes-eriksen** [comment]
Regarding NPM. I already got a request to put it on NPM, which I intend to do. However, the name BOB has a naming conflict. I had fun naming it bob, after "builder bob", but realised later that bob is taken name in more ways than one. Eg. uncle bob, and some other things which I can't find this very moment. Any way; I will likely publish this under some prefix, like bob-xml-builder, or something like this.

**Comment by stephan-nordnes-eriksen** [comment]
The package is now published to npm; https://www.npmjs.com/package/bob-xml

Version 0.1.1 should work as expected. If not, then let me know. There are some minor changes to the project setup as well. The npm name is "bob-xml", as "bob" is taken.

Please open a new issue if there is any problems with the repo.

For the future, if this repo gains traction, I will convert it to TypeScript. Coffeescript is in my humble opinion a bit outdated.
